[27/Dec/2023 18:20:56] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:20:56] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:22:11] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:22:12] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:22:12] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:22:12] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:25:21] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:26:41] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:27:00] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:27:12] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:32:01] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:32:27] WARNING [django.request:241] Not Found: /robots.txt
[27/Dec/2023 18:32:27] WARNING [django.server:212] "GET /robots.txt HTTP/1.1" 404 13891
[27/Dec/2023 18:32:32] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:37:15] WARNING [django.server:212] "GET /static/services/js/object-cards.js HTTP/1.1" 404 1840
[27/Dec/2023 18:39:24] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:39:24] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140564
[27/Dec/2023 18:39:25] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:39:25] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140562
[27/Dec/2023 18:39:38] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:39:38] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137875
[27/Dec/2023 18:39:46] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:39:46] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137873
[27/Dec/2023 18:40:10] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-time')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword '' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:40:10] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137687
[27/Dec/2023 18:40:11] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-time')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword '' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:40:11] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137685
[27/Dec/2023 18:40:11] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-time')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'time' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:40:11] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137734
[27/Dec/2023 18:40:12] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-time')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'time' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:40:12] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137733
[27/Dec/2023 18:40:12] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-time')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'time' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:40:12] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137733
[27/Dec/2023 18:40:23] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-date')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:40:23] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137861
[27/Dec/2023 18:40:23] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-date')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:40:23] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137861
[27/Dec/2023 18:40:23] WARNING [django.request:241] Not Found: /favicon.ico
[27/Dec/2023 18:40:24] WARNING [django.request:241] Not Found: /favicon.ico
[27/Dec/2023 18:40:24] WARNING [django.server:212] "GET /favicon.ico HTTP/1.1" 404 13897
[27/Dec/2023 18:40:57] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:40:57] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140558
[27/Dec/2023 18:40:58] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:40:58] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140558
[27/Dec/2023 18:40:58] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:40:58] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140558
[27/Dec/2023 18:40:59] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:40:59] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140556
[27/Dec/2023 18:40:59] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:40:59] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140558
[27/Dec/2023 18:41:00] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:00] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140556
[27/Dec/2023 18:41:00] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:00] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140558
[27/Dec/2023 18:41:11] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:12] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140558
[27/Dec/2023 18:41:12] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:13] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140492
[27/Dec/2023 18:41:13] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:13] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140490
[27/Dec/2023 18:41:13] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:13] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140492
[27/Dec/2023 18:41:14] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:14] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140491
[27/Dec/2023 18:41:14] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:14] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140492
[27/Dec/2023 18:41:22] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:23] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140493
[27/Dec/2023 18:41:23] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:23] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137769
[27/Dec/2023 18:41:23] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:23] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137769
[27/Dec/2023 18:41:23] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:23] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137769
[27/Dec/2023 18:41:24] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:24] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137769
[27/Dec/2023 18:41:27] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:27] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:27] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:27] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:27] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:27] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:27] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:27] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:27] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:27] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:28] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:28] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137775
[27/Dec/2023 18:41:28] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:28] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137775
[27/Dec/2023 18:41:28] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:28] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137775
[27/Dec/2023 18:41:28] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:28] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137775
[27/Dec/2023 18:41:28] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-content')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:28] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137775
[27/Dec/2023 18:41:33] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-title')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:33] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:34] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-title')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:34] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:34] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-title')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:34] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:34] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 7, in items
    return Service.published.all().order_by('-title')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'content' into field. Choices are: description, discount, id, image, is_published, page, price, service_type, service_type_id, slug, sub_service_type, sub_service_type_id, title, unit, video_url
[27/Dec/2023 18:41:34] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 137771
[27/Dec/2023 18:41:34] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:34] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140552
[27/Dec/2023 18:41:35] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:35] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140550
[27/Dec/2023 18:41:35] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:35] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140550
[27/Dec/2023 18:41:35] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:35] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140550
[27/Dec/2023 18:41:35] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:41:35] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140550
[27/Dec/2023 18:42:32] ERROR [django.request:241] Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 122, in _urls
    paginator_page = self.paginator.page(page)
                     ^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 73, in paginator
    return paginator.Paginator(self._items(), self.limit)
                               ^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 61, in _items
    return self.items()
           ^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/stroytechmontazh/config/sitemaps.py", line 12, in items
    return Article.published.all().order_by('-date_published')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1699, in order_by
    obj.query.add_ordering(*field_names)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 2240, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/home/inside/code/django_stroytechmontazh/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1759, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_published' into field. Choices are: content, id, image, is_published, slug, time_create, time_update, title, topic, topic_id
[27/Dec/2023 18:42:32] ERROR [django.server:212] "GET /sitemap.xml HTTP/1.1" 500 140552
